#!/bin/bash

# $1: folder that contains the .gcda and .gcno files
# $2: path to .info file, output of lcov
# $3: output path for website generated by gentml

echo ""
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "generating test coverage"
echo "the coverage is based on .gcda and .gcno files which are generated by running the test binary"
echo "this means you should run the tests again to get newest coverage information"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo ""

# it's okay to only test for gcda since they are generated by running the test binary
# and gcno are generated by the compiler
for f in $1/*.gcda; do
    if test -f "$f";then
        lcov -c --directory $1 --output-file $2
        genhtml $2 --output-directory $3
        chromium-browser $3/index.html
    else
        echo ""
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo "no gcno files found, you need to run the test first"
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo ""
    fi
    break
done
